// apress/pro-react/c1-simple-app/app/App.jsx
import React, {Component} from 'react'
import ReactDOM from 'react-dom'

import TodoList from './Todo/TodoList.jsx'

class App extends Component {
    constructor(props) {
        super(props)
        this.state = {
            title: "Todo List",
            items: [
                {action: "Learn HTML", done: true},
                {action: "Learn CSS", done: true},
                {action: "Learn JavaScript", done: true},
                {action: "Learn React", done: false},
                {action: "Learn Angular", done: false}
            ]
        }
        this.handleClick = this.handleClick.bind(this)
    }

    handleClick() {
        let newName = this.refs.item.value;

        this.setState({
            items: [
                ...this.state.items,
                {action: newName, done: false}
            ]
        })
    }

    render() {
        return(
            <div className="container">
                <h3 className="bg-primary p-a-1">{this.state.title}</h3>
                <div className="m-t-1 m-b-1">
                    <input type="text" ref="item" className="form-control" placeholder="Enter todo action"/>
                    <button className="btn btn-primary m-t-1" onClick={this.handleClick}>Add</button>
                </div>
                <TodoList items={this.state.items} />
            </div>
        )
    }
}

ReactDOM.render(<App />, document.getElementById("app"))

// apress/pro-angular/c2-first-angular-app/app/app.component.ts
import {Component} from '@angular/core'
import { Model, TodoItem } from './model'

@Component({
    selector: 'todo-app',
    templateUrl: 'app/app.component.html'
})

export class AppComponent {
    model = new Model()

    getName() {
        return this.model.user;
    }

    getTodoItems() {
        return this.model.items.filter(item => !item.done);
    }

    addItem(item: string){
        this.model.items.push(new TodoItem(item, false))
    }
}

<div class="m-a-1">
    <h3 class="bg-primary p-a-1">{{ getName() }}'s Todo List</h3>
    <div class="m-t-1 m-b-1">
        <input type="text" class="form-control" #todoText />
        <button class="btn btn-primary m-t-1" (click)="addItem(todoText.value)">Add</button>
    </div>
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Description</th>
                <th>Mark as completed</th>
                <th>Done</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let item of getTodoItems(); let i = index">
                <td>{{ i + 1 }}</td>
                <td>{{ item.action }}</td>
                <td>
                    <input type="checkbox" [(ngModel)]="item.done" />
                </td>
                <td [ngSwitch]="item.done">
                    <span *ngSwitchCase="true">Yes</span>
                    <span *ngSwitchDefault>No</span>
                </td>
            </tr>
        </tbody>
    </table>
</div>
